# Fly.io configuration for n8n deployment
# NOTE: app name and primary_region are overridden by deploy.sh from config.yaml values
app = "pocket-n8n"
primary_region = "fra"

[build]
  dockerfile = "Dockerfile"

[env]
  NODE_ENV = "production"
  N8N_HOST = "0.0.0.0"
  N8N_PORT = "5678"
  N8N_PROTOCOL = "https"
  N8N_METRICS = "true"
  # These will be set via fly secrets/env vars:
  # WEBHOOK_URL, N8N_LOG_LEVEL, GENERIC_TIMEZONE, N8N_BASIC_AUTH_*, N8N_ENCRYPTION_KEY

[http_service]
  internal_port = 5678
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  
  [http_service.concurrency]
    type = "requests"
    hard_limit = 100
    soft_limit = 80

[[http_service.checks]]
  grace_period = "30s"
  interval = "15s"
  method = "GET"
  timeout = "10s"
  path = "/"

[mounts]
  source = "n8n_data"
  destination = "/home/node/.n8n"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

[metrics]
  port = 8080
  path = "/metrics"